apps/product/urls.py
from django.urls import path

from .views import (
    ProductListView,
    BatchListView,
    ProductBarcodeListView,
    ProductImageView,
    PTFileEntryListView,
    PTFileEntryListAPIView,
    PTFileEntryListView,
    PTFileEntryUpdateAPIView,
    PTFileEntryAPIView,
    PTFileEntryView,
    UploadFileView,
    ExportPTFilesView,
    ExportImagesAPIView,
    MarkPOExportedView,
    ManualFeedingBrandSelectionView,
    ManualFeedingFormView,
    ArticleAutocompleteAPIView,
)

app_name = "product"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("list/", ProductListView.as_view(), name="product_list"),
    path("barcode/list/", ProductBarcodeListView.as_view(), name="barcode_list"),
    path(
        "upload_product_image/", ProductImageView.as_view(), name="upload_product_image"
    ),
    path(
        "upload_tag_image/<int:id>/",
        ProductImageView.as_view(),
        name="upload_tag_image",
    ),
    path(
        "upload_z_file/<int:batch_id>", UploadFileView.as_view(), name="upload_z_file"
    ),
    path("ptfile_entry/", PTFileEntryView.as_view(), name="ptfile_entry"),
    path("ptfile/batches/", BatchListView.as_view(), name="batch_list"),
    path(
        "ptfile_list/<int:batch_id>/", PTFileEntryListView.as_view(), name="ptfile_list"
    ),
    path(
        "export_images/<int:batch_id>/",
        ExportImagesAPIView.as_view(),
        name="export_images",
    ),
    path("api/ptfile_entry/", PTFileEntryAPIView.as_view(), name="api_ptfile_entry"),
    path(
        "api/ptfile_update/",
        PTFileEntryUpdateAPIView.as_view(),
        name="api_ptfile_update",
    ),
    path(
        "api/ptfile_list/<int:batch_id>/",
        PTFileEntryListAPIView.as_view(),
        name="api_ptfile_list",
    ),
    path(
        "export-batch-to-excel/<int:batch_id>/",
        ExportPTFilesView.as_view(),
        name="export_ptfiles",
    ),
    path(
        "export_po/<int:batch_id>/", MarkPOExportedView.as_view(), name="export_for_po"
    ),
    # Manual Feeding URLs
    path(
        "manual-feeding/",
        ManualFeedingBrandSelectionView.as_view(),
        name="manual_feeding_brand_selection",
    ),
    path(
        "manual-feeding/form/<int:brand_id>/",
        ManualFeedingFormView.as_view(),
        name="manual_feeding_form",
    ),
    # Article Autocomplete API
    path(
        "api/article-autocomplete/<int:brand_id>/",
        ArticleAutocompleteAPIView.as_view(),
        name="article_autocomplete",
    ),
]

apps/user/urls.py
from django.urls import path

from .views import UserLoginView, UserLogoutView, UserRegisterView

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    path('dimplecollection/admin/', admin.site.urls),
    path('product/', include('apps.product.urls')),
    path('department/', include('apps.department.urls')),
    path('user/', include('apps.user.urls')),
    path('po/', include('apps.procurement.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('user:login'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/templates/includes/footer.html
{% load static %}

<footer class="main-footer">

  <strong>&copy; Dimple Collection</strong>

</footer>

apps/templates/includes/modal.html
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- Modal Title Placeholder -->
          <h5 class="modal-title" id="successModalLabel">Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Message Placeholder -->

        </div>
        <div class="modal-footer">
          <button type="button" id="okbtn" class="btn btn-primary" data-dismiss="modal">OK</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="quantityModal" tabindex="-1" role="dialog" aria-labelledby="quantityModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- Modal Title Placeholder -->
          <h5 class="modal-title" id="quantityModalLabel">Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Message Placeholder -->

        </div>
        <div class="modal-footer">
          <button type="button" id="cancelbtn" class="btn btn-danger" data-dismiss="modal">Cancel</button>
          <button type="button" id="updateDataButton" class="btn btn-primary" data-dismiss="modal">Update</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- Modal Title Placeholder -->
          <h5 class="modal-title" id="errorModalLabel">Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Message Placeholder -->

        </div>
        <div class="modal-footer">
          <button type="button" id="cancelbtn" class="btn btn-danger" data-dismiss="modal">OK</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="poModal" tabindex="-1" role="dialog" aria-labelledby="quantityModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <!-- Modal Title Placeholder -->
          <h5 class="modal-title" id="quantityModalLabel">Message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Message Placeholder -->

        </div>
        <div class="modal-footer">
          <button type="button" id="okbtn2" class="btn btn-primary" data-dismiss="modal">Ok</button>
        </div>
      </div>
    </div>
  </div>

apps/templates/includes/navigation-dark.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'dashboardv3' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

apps/templates/includes/navigation-light.html
  {% load static %}
  
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'product:product_list' %}" class="nav-link">Home</a>
      </li>
      {% if request.user.is_authenticated %}
        {% if request.user.is_superuser %}
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
          </li>
        {% else %}
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
          </li>
        {% endif %}
      {% else %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'user:login' %}" class="nav-link">Sign In</a>
        </li>
      {% endif %}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

apps/templates/includes/original-sidebar.html
{% load i18n static customtags %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="Dimple Collection Logo" class="brand-image img-circle elevation-3"
      style="opacity: .8">
    <span class="brand-text font-weight-light">Dimple Collection</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        {% if request.user.is_authenticated %}
          <a href="#" class="d-block">{{request.user.username}}</a>
        {% else %}
          <a href="#" class="d-block">Alexander Pierce</a>
        {% endif %}        
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      {% include 'includes/menu-list.html' %}
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

apps/templates/includes/paginator.html
{% load static %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">&laquo;&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
            <span aria-hidden="true">&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
</nav>

apps/templates/includes/scripts.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

apps/templates/includes/sidebar-list.html
{% load i18n static customtags %}

<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
    {% admin_get_menu as app_list %}
    {% if app_list %}
    {% for app in app_list %}
    {% if app.has_perms and not app.pinned %}
    <li class="nav-item {% if 'dashboard' in parent %} menu-open {% endif %}">
        <a class="nav-link {% if app_label != app.label and app.url not in request.path|urlencode %} collapsed{% endif %}"
        data-bs-toggle="collapse" data-bs-target="#submenu-{{ app.app_label }}" href="{{ app.url }}">
        <i class="nav-icon {{ app.icon }}"></i>
        <p>
        {{ app.label|slice:10 }}{% if app.label|length > 10 %}..{% endif %}
        <i class="right fas fa-angle-left"></i>
        </p>
        </a>

        {% if app.models %}
        <ul class="nav nav-treeview">
        {% for model in app.models %}
        {% if model.url %}
        <li class="nav-item">
            <a class="nav-link {% if 'bootstrap-tables' in segment or model.url in request.path|urlencode %} active {% endif %}"
            href="{{ model.url }}">
            <i class="far fa-circle nav-icon"></i>
            <p>{{ model.label }}</p>
            </a>
        </li>
        {% else %}
        <li class="nav-item">{{ model.label }}</li>
        {% endif %}
        {% endfor %}
        </ul>
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
    <li class="nav-item {% if 'product' in parent %} menu-open {% endif %}">
        <a href="#" class="nav-link {% if 'product' in parent %} active {% endif %}">
        <i class="nav-icon fas fa-th"></i>
        <p>
            Product
            <i class="fas fa-angle-left right"></i>
        </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
            <a href="{% url 'product:product_list' %}" class="nav-link {% if 'product_list' in segment %} active {% endif %}">
                <i class="far fa-plus-square nav-icon"></i>
                <p>Product List & Entry</p>
            </a>
            </li>
            <li class="nav-item">
            <a href="{% url 'product:ptfile_entry' %}" class="nav-link {% if 'ptfile_entry' in segment %} active {% endif %}">
                <i class="far fa-plus-square nav-icon"></i>
                <p>PTFile Entry</p>
            </a>
            </li>
            <li class="nav-item">
            <a href="{% url 'product:batch_list' %}" class="nav-link {% if 'batch_list' in segment %} active {% endif %}">
                <i class="far fa-plus-square nav-icon"></i>
                <p>PTFile List</p>
            </a>
            </li>
            {% if request.user.user_type != 'FT' %}
            <li class="nav-item">
            <a href="{% url 'product:barcode_list' %}" class="nav-link {% if 'barcode_list' in segment %} active {% endif %}">
                <i class="fas fa-table nav-icon"></i>
                <p>Barcode List</p>
            </a>
            </li>
            {% endif %}
        </ul>
    </li>

    {% if request.user.user_type != 'FT' and request.user.user_type != 'BT'%}
    <li class="nav-item">
        <a href="{% url 'user:register' %}" class="nav-link">
        <i class="fa fa-user-plus nav-icon"></i>
        <p>Register</p>
        </a>
    </li>
    {% endif %}
    {% endif %}
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a href="{% url 'user:logout' %}" class="nav-link">
        <i class="fa fa-sign-out-alt nav-icon"></i>
        <p>Logout</p>
        </a>
    </li>
    {% else %}
    <li class="nav-item">
        <a href="{% url 'user:login' %}" class="nav-link">
        <i class="fa fa-sign-in-alt nav-icon"></i>
        <p>Login</p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'user:register' %}" class="nav-link">
        <i class="fa fa-user-plus nav-icon"></i>
        <p>Register</p>
        </a>
    </li>        
    {% endif %}        
</ul>

apps/templates/includes/sidebar.html
{% load i18n static customtags %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{% url 'product:product_list' %}" class="brand-link">
    <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="Dimple Collection Logo" class="brand-image img-circle elevation-3"
      style="opacity: .8">
    <span class="brand-text font-weight-light">Dimple Collection</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      {% comment %} <div class="image">
        <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
      </div> {% endcomment %}
      <div class="info">
        {% if request.user.is_authenticated %}
          <a href="{% url 'product:product_list' %}" class="d-block">{{request.user.email}}</a>
        {% else %}
          <a href="{% url 'product:product_list' %}" class="d-block">Guest</a>
        {% endif %}        
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      {% include 'includes/sidebar-list.html' %}
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>