apps/procurement/urls.py
from django.urls import path

from .views import (
    ProcurementOrderCreateView,
    ProcurementOrderListView,
    ProcurementOrderRetrieveUpdateView,
    ProcurementOrderActionView,
    ProcurementOrderBottomCreateView,
    ProcurementOrderKidsCreateView,
    ProcurementOrderBottomRetrieveUpdateView,
    ProcurementOrderKidsRetrieveUpdateView
    # ProcurementOrderUpdateView
)


app_name = "procurement"


urlpatterns = [
    path(
        "create/", ProcurementOrderCreateView.as_view(), name="create_procurement_order"
    ),
    path(
        "create_bottom/", ProcurementOrderBottomCreateView.as_view(), name="create_procurement_order_bottom"
    ),
    path(
        "create_kids/", ProcurementOrderKidsCreateView.as_view(), name="create_procurement_order_kids"
    ),
    path("list/", ProcurementOrderListView.as_view(), name="procurement_order_list"),
    path('action/<int:order_id>/<str:action>/', ProcurementOrderActionView.as_view(), name='procurement_order_action'),
    path("details/<int:pk>/", ProcurementOrderRetrieveUpdateView.as_view(), name="procurement_detail"),
    path("details_bottom/<int:pk>/", ProcurementOrderBottomRetrieveUpdateView.as_view(), name="procurement_bottom_detail"),
    path("details_kids/<int:pk>/", ProcurementOrderKidsRetrieveUpdateView.as_view(), name="procurement_kids_detail"),
    # path('update/<int:pk>/', ProcurementOrderUpdateView.as_view(), name='update_procurement_order'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    path('dimplecollection/admin/', admin.site.urls),
    path('product/', include('apps.product.urls')),
    path('department/', include('apps.department.urls')),
    path('user/', include('apps.user.urls')),
    path('po/', include('apps.procurement.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('user:login'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/templates/pages/procurement_order/procurement_order_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Procurement Order List{% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Procurement Order List</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Procurement Order List</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      {% csrf_token %}
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- /.card -->

            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">
                <div id="loader" style="display:flex;height: 400px;" class=" justify-content-center align-items-center">
                  <div class="spinner-border" role="status">
                    <span class="sr-only">Loading...</span>
                  </div>
                </div>
                <table id="example1" class="table table-bordered table-striped" style="display: none;">
                  <thead>
                  <tr>
                    <th>Status</th>
                    <th>Brand</th>
                    <th>Intent Number</th>
                    <th>Terms of Shipment</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.status }}</td>
                        <td>{{ order.brand.brand_name }}</td>
                        <td>{{ order.intent_number }}</td>
                        <td>{{ order.terms_of_shipment }}</td>
                        <td>{{ order.created_at }}</td>
                        <td>{{ order.updated_at }}</td>
                        <td>
                          {% if order.type == 'BOTTOM' %}
                          <a href="{% url 'procurement:procurement_bottom_detail' order.id %}"><button class="btn btn-primary">View</button></a>
                          {% elif order.type == 'KIDS' %}
                          <a href="{% url 'procurement:procurement_kids_detail' order.id %}"><button class="btn btn-primary">View</button></a>
                          {% else %}
                          <a href="{% url 'procurement:procurement_detail' order.id %}"><button class="btn btn-primary">View</button></a>
                          {% endif %}
                          {% if is_admin and order.admin_approve_status == 'pending' %}
                          <a href="{% url 'procurement:procurement_order_action' order.id 'approve' %}" class="btn btn-success"><i class="fas fa-check"></i></a>
                          <a href="{% url 'procurement:procurement_order_action' order.id 'reject' %}" class="btn btn-danger"><i class="fas fa-times"></i></a>
                          {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <div class="pagination-container m-2" style="text-align: right;">
                  {% include 'includes/paginator.html' %}
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    
    <!-- /.content -->
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  function showOverlay() {
    // Create overlay elements
    var overlayWrapper = document.createElement('div');
    overlayWrapper.className = 'overlay-wrapper';

    var overlay = document.createElement('div');
    overlay.className = 'overlay dark';
    overlay.innerHTML = '<i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Loading...</div>';

    // Append overlay elements to the body
    overlayWrapper.appendChild(overlay);
    document.body.appendChild(overlayWrapper);
  }

  function hideOverlay() {
    // Remove overlay elements from the body
    var overlayWrapper = document.querySelector('.overlay-wrapper');
    overlayWrapper.parentNode.removeChild(overlayWrapper);
  }
  $(function () {
    showOverlay();
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false, "paging": false, "info": false, "ordering": false,
      "initComplete": function () {
        hideOverlay();
        $('#example1').show();
        $('#loader').hide();
      }
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": false,
      "lengthChange": false,
      "searching": false,
      "ordering": false,
      "info": false,
      "autoWidth": false,
      "responsive": true,
    });
  });

</script>
{% endblock extra_scripts %}