apps/product/urls.py
from django.urls import path

from .views import (
    ProductListView,
    BatchListView,
    ProductBarcodeListView,
    ProductImageView,
    PTFileEntryListView,
    PTFileEntryListAPIView,
    PTFileEntryListView,
    PTFileEntryUpdateAPIView,
    PTFileEntryAPIView,
    PTFileEntryView,
    UploadFileView,
    ExportPTFilesView,
    ExportImagesAPIView,
    MarkPOExportedView,
    ManualFeedingBrandSelectionView,
    ManualFeedingFormView,
    ArticleAutocompleteAPIView,
)

app_name = "product"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("list/", ProductListView.as_view(), name="product_list"),
    path("barcode/list/", ProductBarcodeListView.as_view(), name="barcode_list"),
    path(
        "upload_product_image/", ProductImageView.as_view(), name="upload_product_image"
    ),
    path(
        "upload_tag_image/<int:id>/",
        ProductImageView.as_view(),
        name="upload_tag_image",
    ),
    path(
        "upload_z_file/<int:batch_id>", UploadFileView.as_view(), name="upload_z_file"
    ),
    path("ptfile_entry/", PTFileEntryView.as_view(), name="ptfile_entry"),
    path("ptfile/batches/", BatchListView.as_view(), name="batch_list"),
    path(
        "ptfile_list/<int:batch_id>/", PTFileEntryListView.as_view(), name="ptfile_list"
    ),
    path(
        "export_images/<int:batch_id>/",
        ExportImagesAPIView.as_view(),
        name="export_images",
    ),
    path("api/ptfile_entry/", PTFileEntryAPIView.as_view(), name="api_ptfile_entry"),
    path(
        "api/ptfile_update/",
        PTFileEntryUpdateAPIView.as_view(),
        name="api_ptfile_update",
    ),
    path(
        "api/ptfile_list/<int:batch_id>/",
        PTFileEntryListAPIView.as_view(),
        name="api_ptfile_list",
    ),
    path(
        "export-batch-to-excel/<int:batch_id>/",
        ExportPTFilesView.as_view(),
        name="export_ptfiles",
    ),
    path(
        "export_po/<int:batch_id>/", MarkPOExportedView.as_view(), name="export_for_po"
    ),
    # Manual Feeding URLs
    path(
        "manual-feeding/",
        ManualFeedingBrandSelectionView.as_view(),
        name="manual_feeding_brand_selection",
    ),
    path(
        "manual-feeding/form/<int:brand_id>/",
        ManualFeedingFormView.as_view(),
        name="manual_feeding_form",
    ),
    # Article Autocomplete API
    path(
        "api/article-autocomplete/<int:brand_id>/",
        ArticleAutocompleteAPIView.as_view(),
        name="article_autocomplete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    path('dimplecollection/admin/', admin.site.urls),
    path('product/', include('apps.product.urls')),
    path('department/', include('apps.department.urls')),
    path('user/', include('apps.user.urls')),
    path('po/', include('apps.procurement.urls')),
    path('', RedirectView.as_view(url=reverse_lazy('user:login'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/product/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Product, PTFileEntry
from apps.department.models import Brand, Department, Color


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["department", "category", "subcategory", "brand", "article_number"]
        widgets = {
            "department": forms.TextInput(attrs={"class": "form-control"}),
            "category": forms.TextInput(attrs={"class": "form-control"}),
            "subcategory": forms.TextInput(attrs={"class": "form-control"}),
            "brand": forms.TextInput(attrs={"class": "form-control"}),
            "article_number": forms.TextInput(attrs={"class": "form-control"}),
        }


class UploadFileForm(forms.Form):
    file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"class": "form-control my-4"})
    )


class BrandSelectionForm(forms.Form):
    brand = forms.ModelChoiceField(
        queryset=Brand.objects.all(),
        empty_label="Select a Brand",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )


class ManualFeedingForm(forms.Form):
    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
        empty_label="Select Department",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    article = forms.CharField(
        max_length=128,
        widget=forms.TextInput(
            attrs={
                "class": "form-control article-autocomplete",
                "placeholder": "Enter Article Number",
                "autocomplete": "off",
                "data-autocomplete": "true",
            }
        ),
    )
    color = forms.ModelChoiceField(
        queryset=Color.objects.all(),
        empty_label="Select Color",
        widget=forms.Select(attrs={"class": "form-control select2"}),
    )
    number_of_rows = forms.IntegerField(
        min_value=1,
        max_value=100,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": "Enter number of rows"}
        ),
    )
    photo_data = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,  # We'll validate this manually
    )

    def clean_photo_data(self):
        photo_data = self.cleaned_data.get("photo_data")
        if not photo_data:
            raise forms.ValidationError(
                "Photo is required. Please capture a photo before submitting."
            )

        if not photo_data.startswith("data:image/"):
            raise forms.ValidationError(
                "Invalid image format. Please capture a new photo."
            )

        return photo_data

apps/product/views.py
from typing import Any
import uuid
import base64
import zipfile
from django.db.models.query import QuerySet

from django.shortcuts import redirect
from django.views import generic
from django.http import JsonResponse, HttpResponse
from django.views import View
from django.core.files.base import ContentFile
from django.contrib.auth.mixins import LoginRequiredMixin
from django_pandas.io import read_frame
from django.views.generic import ListView
from django.db.models import Sum
from django.db import transaction

from apps.utils.utils import SideBarSelectedMixin
from apps.product.models import Product, ProductImage, ProductBarcode
from apps.product.forms import (
    ProductForm,
    UploadFileForm,
    BrandSelectionForm,
    ManualFeedingForm,
)
from apps.product.utils import (
    get_or_create_product,
    check_product_is_unique_or_merge,
    clean_extracted_data,
)
from apps.product.tasks import process_image_data

from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from openpyxl import load_workbook
from io import BytesIO
import pandas as pd
import json
import binascii

from apps.product.models import (
    Product,
    ProductImage,
    ProductBarcode,
    PTFileEntry,
    PTStatus,
    PTFileBatch,
)
from apps.department.models import Department, Brand, Color, Category, SubCategory, Size
from apps.product.serializers import (
    PTFileEntrySerializer,
    PTFileEntryCreateSerializer,
    DepartmentNestedSerializer,
    BrandSerializer,
    SubCategorySerializer,
    CategorySerializer,
    ColorSerializer,
    SizeSerializer,
)
from apps.product.mappers import (
    pt_entry_to_product_mapper,
    pt_entry_to_pt_entry_mapper,
    z_order_upload_to_dict_mapper,
)
from apps.product.tasks import process_image_data


class ProductListView(SideBarSelectedMixin, LoginRequiredMixin, generic.ListView):
    model = Product
    template_name = "pages/product/product_list.html"
    login_url = "user:login"
    context_object_name = "products"
    parent = "product"
    segment = "product_list"
    paginate_by = 6
    ordering = "-created_at"


class ProductBarcodeListView(
    SideBarSelectedMixin, LoginRequiredMixin, generic.ListView
):
    model = PTFileBatch
    template_name = "pages/product/barcode_list.html"
    login_url = "user:login"
    context_object_name = "batch_list"
    parent = "product"
    segment = "barcode_list"
    paginate_by = 6
    ordering = "-created_at"


class ProductEntryView(SideBarSelectedMixin, LoginRequiredMixin, generic.TemplateView):
    template_name = "pages/product/product_entry_photo.html"
    form_class = ProductForm
    parent = "product"
    segment = "product_list"

    def get_context_data(self):
        data = self.request.GET
        context = super().get_context_data()
        context["photo"] = "Cloth" if data.get("page") == "1" else "Tag"
        context["show_fields"] = data.get("page") == "1"
        if data.get("page") == "3":
            id = data.get("id")
            product = Product.objects.get(id=id)
            context["form"] = self.form_class(instance=product)
            context["product"] = product
        return context

    def get(self, request):
        if request.GET.get("page") == "3":
            context = self.get_context_data()
            self.template_name = "pages/product/product_entry.html"
            return self.render_to_response(context=context)
        return super().get(request=request)

    def post(self, request):
        id = request.GET.get("id")
        instance = Product.objects.get(id=id)
        form = self.form_class(request.POST, instance=instance)
        if form.is_valid():
            form.save()
        return redirect("product:product_entry")


class ProductImageView(View):
    def post(self, request, *args, **kwargs):
        try:
            data = request.POST
            image_data = data.get("image").split(",")[1]
            article_data = data.get("article_number")
            color_data = data.get("color")
            print(len(image_data))
            while len(image_data) % 4 != 0:
                image_data += "="
            print(image_data)
            decoded_image_data = base64.b64decode(image_data)
            image_name = str(uuid.uuid4())
            image_file = ContentFile(decoded_image_data, name=f"{image_name}.png")
            product_instance = ProductImage.objects.create(
                product_image=image_file,
                metadata={"article_number": article_data, "color": color_data},
            )
            context = {"product_id": product_instance.id}
            print("product_id", product_instance.id)
            return JsonResponse({"status": "success", "context": context})
        except Exception as e:
            print(e)
            return JsonResponse({"status": "error", "message": str(e)})

    def patch(self, request, *args, **kwargs):
        print("hello")
        product_id = kwargs.get("id")

        # tag_image = request.FILES.get("tag_image")
        try:
            image_data = request.body.decode("utf-8").split(",")[1]
            while len(image_data) % 4 != 0:
                image_data += "="
            decoded_image_data = base64.b64decode(image_data)
            image_name = str(uuid.uuid4())
            image_file = ContentFile(decoded_image_data, name=f"{image_name}.png")
            try:
                product_image_instance = ProductImage.objects.get(id=product_id)
                product_image_instance.tag_image = image_file
                product_image_instance.save()
                tag_image = product_image_instance.tag_image.name.split("/")[1]
                print("tag_image", tag_image)
                process_image_data.delay(tag_image, product_image_instance.id)
                print("product_id_after", "done save product")
                context = {}
            except Exception as e:
                print(e)
                context = {}
            return JsonResponse({"status": "success", "context": context})
        except Exception as e:
            print(e)
            return JsonResponse({"status": "error", "message": str(e)})


class UploadFileView(SideBarSelectedMixin, generic.ListView):
    form_class = UploadFileForm
    model = PTFileBatch
    success_url = "product:barcode_list"
    template_name = "pages/product/barcode_batch_detail.html"
    parent = "product"
    segment = "barcode_list"
    paginate_by = 6

    def get_queryset(self) -> QuerySet[Any]:
        batch_id = self.kwargs.get("batch_id")
        batch = PTFileBatch.objects.get(id=batch_id)
        ptfile_entry_ids = batch.ptfile_entry_ids
        ptfile_entries = PTFileEntry.objects.filter(id__in=ptfile_entry_ids).order_by(
            "product__article_number", "size__size_value"
        )
        if batch.is_file_uploaded:
            queryset = ProductBarcode.objects.filter(pt_entry__in=ptfile_entries)
        else:
            queryset = ptfile_entries
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        upload_form = UploadFileForm()
        batch_id = self.kwargs.get("batch_id")
        batch = PTFileBatch.objects.get(id=batch_id)
        barcode_entries = False
        if batch.is_file_uploaded:
            barcode_entries = True
        context["batch"] = batch
        context["upload_form"] = upload_form
        context["barcode_entries"] = barcode_entries
        return context

    def post(self, request, *args, **kwargs):
        batch_id = kwargs.get("batch_id")
        form = self.form_class(request.POST, request.FILES)
        self.object_list = self.get_queryset()
        try:
            if form.is_valid():
                uploaded_file = request.FILES["file"]
                try:
                    batch = PTFileBatch.objects.get(id=batch_id)
                except Exception as e:
                    print(e)
                    return self.render_to_response(status=status.HTTP_400_BAD_REQUEST)

                ptfile_entry_ids = batch.ptfile_entry_ids
                ptfile_entries = PTFileEntry.objects.filter(id__in=ptfile_entry_ids)
                workbook = load_workbook(uploaded_file, read_only=True)
                sheet = workbook.active
                pt_entry_frequency = {}
                barcode_data_list = []
                errors = []
                for row in sheet.iter_rows(min_row=2):
                    row = [cell.value for cell in row]
                    if row[0] is not None:
                        barcode_row = z_order_upload_to_dict_mapper(row)
                        pt_entry_id = barcode_row.get("pt_entry_id")
                        pt_entry_frequency[pt_entry_id] = (
                            pt_entry_frequency.get(pt_entry_id, 0) + 1
                        )
                        barcode_data_list.append(barcode_row)
                for entry in ptfile_entries:
                    expected_quantity = entry.quantity
                    provided_quantity = pt_entry_frequency.get(entry.id, 0)
                    print(f"{entry.id} -> {expected_quantity} == {provided_quantity}")
                    if expected_quantity != provided_quantity:
                        errors.append(
                            f"Quantity mismatch for PT Entry id: {entry.id}. Expected: {expected_quantity}, Provided: {provided_quantity}"
                        )
                if errors:
                    print(errors)
                    context = self.get_context_data()
                    context["errors"] = errors
                    return self.render_to_response(
                        context, status=status.HTTP_400_BAD_REQUEST
                    )

                product_barcodes = [
                    ProductBarcode(
                        pt_entry_id=barcode_data.get("pt_entry_id"),

apps/templates/pages/product/barcode_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Barcode List{% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Batch Details</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Batch Details</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- /.card -->

            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">
                <div id="loader" style="display:flex;height: 400px;" class=" justify-content-center align-items-center" >
                  <div class="spinner-border" role="status">
                    <span class="sr-only">Loading...</span>
                  </div>
                </div>
                <table id="example1" class="table table-bordered table-striped" style="display: none;">
                  <thead>
                  <tr>
                    <th>Batch id</th>
                    <th>Is Image Export</th>
                    <th>Is Export</th>
                    <th>Is Export For PO</th>
                    <th>Is File Uploaded</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for item in batch_list %}
                    <tr class="unread {% if not item.is_file_uploaded %}bg-danger{% endif %}">
                        <td>
                            <h6 class="mb-1">{{ item.batch_id }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-1">{{ item.is_image_exported }}</h6>
                      </td>
                      <td>
                        <h6 class="mb-1">{{ item.is_exported }}</h6>
                    </td>
                        <td>
                          <h6 class="mb-1">{{ item.is_exported_for_po }}</h6>
                      </td>
                      <td>
                        <h6 class="mb-1">{{ item.is_file_uploaded }}</h6>
                    </td>
                        <td>
                          <a href="{% url 'product:upload_z_file' item.id %}">
                            <button class="btn btn-primary">View</button>
                        </a>
                        </td>
                    </tr>
                {% endfor %}
                  </tbody>
                </table>
                <div class="pagination-container m-2" style="text-align: right;">
                  {% include 'includes/paginator.html' %}
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    
    <!-- /.content -->
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  function showOverlay() {
    // Create overlay elements
    var overlayWrapper = document.createElement('div');
    overlayWrapper.className = 'overlay-wrapper';

    var overlay = document.createElement('div');
    overlay.className = 'overlay dark';
    overlay.innerHTML = '<i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Loading...</div>';

    // Append overlay elements to the body
    overlayWrapper.appendChild(overlay);
    document.body.appendChild(overlayWrapper);
  }

  function hideOverlay() {
    // Remove overlay elements from the body
    var overlayWrapper = document.querySelector('.overlay-wrapper');
    overlayWrapper.parentNode.removeChild(overlayWrapper);
  }
  $(function () {
    showOverlay();
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false, "paging": false, "info": false, "ordering": false,
      "initComplete": function () {
        hideOverlay();
        $('#example1').show();
        $('#loader').hide();
      }
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": false,
      "lengthChange": false,
      "searching": false,
      "ordering": false,
      "info": false,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
{% endblock extra_scripts %}

apps/templates/pages/product/product_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Product List{% endblock title %}
{% block extrastyle %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Product List</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product List</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <h3 class="card-title">Product List</h3>
                    <div class="row">
                      <div class="pr-4">
                        <a href="{% url 'product:product_list' %}" >
                          <button type="button" class="btn btn-primary px-2" title="Reload Page" data-toggle="tooltip"><span><i class="fa fa-sync-alt"></i></span></button>
                        </a>
                      </div>
                      <div>
                        <a href="{% url 'product:manual_feeding_brand_selection' %}">
                          <button type="button" class="btn btn-block btn-primary" title="Add new Product" data-toggle="tooltip">Add Product</button>
                        </a>
                      </div>
                    </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div id="loader" style="display:flex; height: 400px;" class=" justify-content-center align-items-center" >
                  <div class="spinner-border" role="status">
                    <span class="sr-only">Loading...</span>
                  </div>
                </div>
                <table id="example1" class="table table-bordered table-striped" style="display: none;">
                  <thead>
                  <tr>
                    <th>Article Number</th>
                    <th>Department</th>
                    <th>Category</th>
                    <th>Sub Category</th>
                    <th>Brand</th>
                    <th>Created At</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for item in products %}
                    <tr class="unread">
                        <td>
                            <h6 class="mb-1">{{ item.article_number }}</h6>
                        </td>
                        <td>
                            <h6 class="mb-1">{{ item.department }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-1">{{ item.category.category_name }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-1">{{ item.subcategory }}</h6>
                        </td>
                        <td>
                            <h6 class="mb-1">{{ item.brand }}</h6>
                        </td>
                      <td>
                        <h6 class="mb-1">{{ item.created_at }}</h6>
                      </td>
                    </tr>
                {% endfor %}
                  </tbody>
                </table>
              <div class="pagination-container m-2" style="text-align: right;">
                {% include 'includes/paginator.html' %}
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}
{% block extra_scripts %}
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- Page specific script -->
<script>
  function showOverlay() {
    // Create overlay elements
    var overlayWrapper = document.createElement('div');
    overlayWrapper.className = 'overlay-wrapper';

    var overlay = document.createElement('div');
    overlay.className = 'overlay dark';
    overlay.innerHTML = '<i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Loading...</div>';

    // Append overlay elements to the body
    overlayWrapper.appendChild(overlay);
    document.body.appendChild(overlayWrapper);
  }

  function hideOverlay() {
    // Remove overlay elements from the body
    var overlayWrapper = document.querySelector('.overlay-wrapper');
    overlayWrapper.parentNode.removeChild(overlayWrapper);
  }


  $(function () {
    showOverlay();
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false, "paging": false, "info": false, "ordering": false,
      "initComplete": function () {
        hideOverlay();
        $('#example1').show();
        $('#loader').hide();
      }
    }).buttons().container().appendTo('#example1_wrapper .col-md-6');

    hideOverlay();  
    $('#example1').show();
    $('#loader').hide();
    $('#example2').DataTable({
      "paging": false,
      "lengthChange": false,
      "searching": false,
      "ordering": false,
      "info": false,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock extra_scripts %}